//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTTT.Ejemplo.Persona.WinForm.Ejemplo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrValorSexoField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrClaveUnicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrAPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrAMaternoField;
        
        private int IdCatSexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UTTT.Ejemplo.Persona.WinForm.Ejemplo.CatSexo CatSexoTempField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StrValorSexo {
            get {
                return this.StrValorSexoField;
            }
            set {
                if ((object.ReferenceEquals(this.StrValorSexoField, value) != true)) {
                    this.StrValorSexoField = value;
                    this.RaisePropertyChanged("StrValorSexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrClaveUnica {
            get {
                return this.StrClaveUnicaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrClaveUnicaField, value) != true)) {
                    this.StrClaveUnicaField = value;
                    this.RaisePropertyChanged("StrClaveUnica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StrNombre {
            get {
                return this.StrNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.StrNombreField, value) != true)) {
                    this.StrNombreField = value;
                    this.RaisePropertyChanged("StrNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StrAPaterno {
            get {
                return this.StrAPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.StrAPaternoField, value) != true)) {
                    this.StrAPaternoField = value;
                    this.RaisePropertyChanged("StrAPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string StrAMaterno {
            get {
                return this.StrAMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.StrAMaternoField, value) != true)) {
                    this.StrAMaternoField = value;
                    this.RaisePropertyChanged("StrAMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int IdCatSexo {
            get {
                return this.IdCatSexoField;
            }
            set {
                if ((this.IdCatSexoField.Equals(value) != true)) {
                    this.IdCatSexoField = value;
                    this.RaisePropertyChanged("IdCatSexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.CatSexo CatSexoTemp {
            get {
                return this.CatSexoTempField;
            }
            set {
                if ((object.ReferenceEquals(this.CatSexoTempField, value) != true)) {
                    this.CatSexoTempField = value;
                    this.RaisePropertyChanged("CatSexoTemp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatSexo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CatSexo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StrValor {
            get {
                return this.StrValorField;
            }
            set {
                if ((object.ReferenceEquals(this.StrValorField, value) != true)) {
                    this.StrValorField = value;
                    this.RaisePropertyChanged("StrValor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrDescripcion {
            get {
                return this.StrDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.StrDescripcionField, value) != true)) {
                    this.StrDescripcionField = value;
                    this.RaisePropertyChanged("StrDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Direccion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Direccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrCalleField;
        
        private int IdPersonaField;
        
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StrColonia {
            get {
                return this.StrColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrColoniaField, value) != true)) {
                    this.StrColoniaField = value;
                    this.RaisePropertyChanged("StrColonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StrNumero {
            get {
                return this.StrNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.StrNumeroField, value) != true)) {
                    this.StrNumeroField = value;
                    this.RaisePropertyChanged("StrNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrCalle {
            get {
                return this.StrCalleField;
            }
            set {
                if ((object.ReferenceEquals(this.StrCalleField, value) != true)) {
                    this.StrCalleField = value;
                    this.RaisePropertyChanged("StrCalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Ejemplo.EjemploSoap")]
    public interface EjemploSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _persona del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarPersona", ReplyAction="*")]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarPersonaResponse insertarPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _persona del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editarPersona", ReplyAction="*")]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarPersonaResponse editarPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _persona del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarPersona", ReplyAction="*")]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarPersonaResponse eliminarPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultarGlobalPersonaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarGlobalPersona", ReplyAction="*")]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalPersonaResponse consultarGlobalPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _persona del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarUnicaPersona", ReplyAction="*")]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaPersonaResponse consultarUnicaPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _direccion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDireccion", ReplyAction="*")]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarDireccionResponse insertarDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarDireccionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _direccion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editarDireccion", ReplyAction="*")]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarDireccionResponse editarDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarDireccionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _direccion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDireccion", ReplyAction="*")]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarDireccionResponse eliminarDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarDireccionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultarGlobalDireccionResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarGlobalDireccion", ReplyAction="*")]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalDireccionResponse consultarGlobalDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalDireccionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _direccion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarUnicaDireccion", ReplyAction="*")]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaDireccionResponse consultarUnicaDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaDireccionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultaGlobalSexoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaGlobalSexo", ReplyAction="*")]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultaGlobalSexoResponse consultaGlobalSexo(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultaGlobalSexoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarPersona", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarPersonaRequestBody Body;
        
        public insertarPersonaRequest() {
        }
        
        public insertarPersonaRequest(UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarPersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona _persona;
        
        public insertarPersonaRequestBody() {
        }
        
        public insertarPersonaRequestBody(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona _persona) {
            this._persona = _persona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarPersonaResponseBody Body;
        
        public insertarPersonaResponse() {
        }
        
        public insertarPersonaResponse(UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarPersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertarPersonaResult;
        
        public insertarPersonaResponseBody() {
        }
        
        public insertarPersonaResponseBody(bool insertarPersonaResult) {
            this.insertarPersonaResult = insertarPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editarPersona", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarPersonaRequestBody Body;
        
        public editarPersonaRequest() {
        }
        
        public editarPersonaRequest(UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editarPersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona _persona;
        
        public editarPersonaRequestBody() {
        }
        
        public editarPersonaRequestBody(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona _persona) {
            this._persona = _persona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarPersonaResponseBody Body;
        
        public editarPersonaResponse() {
        }
        
        public editarPersonaResponse(UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editarPersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool editarPersonaResult;
        
        public editarPersonaResponseBody() {
        }
        
        public editarPersonaResponseBody(bool editarPersonaResult) {
            this.editarPersonaResult = editarPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarPersona", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarPersonaRequestBody Body;
        
        public eliminarPersonaRequest() {
        }
        
        public eliminarPersonaRequest(UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarPersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona _persona;
        
        public eliminarPersonaRequestBody() {
        }
        
        public eliminarPersonaRequestBody(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona _persona) {
            this._persona = _persona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarPersonaResponseBody Body;
        
        public eliminarPersonaResponse() {
        }
        
        public eliminarPersonaResponse(UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarPersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool eliminarPersonaResult;
        
        public eliminarPersonaResponseBody() {
        }
        
        public eliminarPersonaResponseBody(bool eliminarPersonaResult) {
            this.eliminarPersonaResult = eliminarPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarGlobalPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarGlobalPersona", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalPersonaRequestBody Body;
        
        public consultarGlobalPersonaRequest() {
        }
        
        public consultarGlobalPersonaRequest(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultarGlobalPersonaRequestBody {
        
        public consultarGlobalPersonaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarGlobalPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarGlobalPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalPersonaResponseBody Body;
        
        public consultarGlobalPersonaResponse() {
        }
        
        public consultarGlobalPersonaResponse(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarGlobalPersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona[] consultarGlobalPersonaResult;
        
        public consultarGlobalPersonaResponseBody() {
        }
        
        public consultarGlobalPersonaResponseBody(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona[] consultarGlobalPersonaResult) {
            this.consultarGlobalPersonaResult = consultarGlobalPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarUnicaPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarUnicaPersona", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaPersonaRequestBody Body;
        
        public consultarUnicaPersonaRequest() {
        }
        
        public consultarUnicaPersonaRequest(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarUnicaPersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona _persona;
        
        public consultarUnicaPersonaRequestBody() {
        }
        
        public consultarUnicaPersonaRequestBody(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona _persona) {
            this._persona = _persona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarUnicaPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarUnicaPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaPersonaResponseBody Body;
        
        public consultarUnicaPersonaResponse() {
        }
        
        public consultarUnicaPersonaResponse(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarUnicaPersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona consultarUnicaPersonaResult;
        
        public consultarUnicaPersonaResponseBody() {
        }
        
        public consultarUnicaPersonaResponseBody(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona consultarUnicaPersonaResult) {
            this.consultarUnicaPersonaResult = consultarUnicaPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDireccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDireccion", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarDireccionRequestBody Body;
        
        public insertarDireccionRequest() {
        }
        
        public insertarDireccionRequest(UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarDireccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarDireccionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion _direccion;
        
        public insertarDireccionRequestBody() {
        }
        
        public insertarDireccionRequestBody(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion _direccion) {
            this._direccion = _direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDireccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDireccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarDireccionResponseBody Body;
        
        public insertarDireccionResponse() {
        }
        
        public insertarDireccionResponse(UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarDireccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarDireccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertarDireccionResult;
        
        public insertarDireccionResponseBody() {
        }
        
        public insertarDireccionResponseBody(bool insertarDireccionResult) {
            this.insertarDireccionResult = insertarDireccionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editarDireccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editarDireccion", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarDireccionRequestBody Body;
        
        public editarDireccionRequest() {
        }
        
        public editarDireccionRequest(UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarDireccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editarDireccionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion _direccion;
        
        public editarDireccionRequestBody() {
        }
        
        public editarDireccionRequestBody(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion _direccion) {
            this._direccion = _direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editarDireccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editarDireccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarDireccionResponseBody Body;
        
        public editarDireccionResponse() {
        }
        
        public editarDireccionResponse(UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarDireccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editarDireccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool editarDireccionResult;
        
        public editarDireccionResponseBody() {
        }
        
        public editarDireccionResponseBody(bool editarDireccionResult) {
            this.editarDireccionResult = editarDireccionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarDireccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarDireccion", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarDireccionRequestBody Body;
        
        public eliminarDireccionRequest() {
        }
        
        public eliminarDireccionRequest(UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarDireccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarDireccionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion _direccion;
        
        public eliminarDireccionRequestBody() {
        }
        
        public eliminarDireccionRequestBody(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion _direccion) {
            this._direccion = _direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarDireccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarDireccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarDireccionResponseBody Body;
        
        public eliminarDireccionResponse() {
        }
        
        public eliminarDireccionResponse(UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarDireccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarDireccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool eliminarDireccionResult;
        
        public eliminarDireccionResponseBody() {
        }
        
        public eliminarDireccionResponseBody(bool eliminarDireccionResult) {
            this.eliminarDireccionResult = eliminarDireccionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarGlobalDireccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarGlobalDireccion", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalDireccionRequestBody Body;
        
        public consultarGlobalDireccionRequest() {
        }
        
        public consultarGlobalDireccionRequest(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalDireccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultarGlobalDireccionRequestBody {
        
        public consultarGlobalDireccionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarGlobalDireccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarGlobalDireccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalDireccionResponseBody Body;
        
        public consultarGlobalDireccionResponse() {
        }
        
        public consultarGlobalDireccionResponse(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalDireccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarGlobalDireccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion[] consultarGlobalDireccionResult;
        
        public consultarGlobalDireccionResponseBody() {
        }
        
        public consultarGlobalDireccionResponseBody(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion[] consultarGlobalDireccionResult) {
            this.consultarGlobalDireccionResult = consultarGlobalDireccionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarUnicaDireccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarUnicaDireccion", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaDireccionRequestBody Body;
        
        public consultarUnicaDireccionRequest() {
        }
        
        public consultarUnicaDireccionRequest(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaDireccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarUnicaDireccionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion _direccion;
        
        public consultarUnicaDireccionRequestBody() {
        }
        
        public consultarUnicaDireccionRequestBody(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion _direccion) {
            this._direccion = _direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarUnicaDireccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarUnicaDireccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaDireccionResponseBody Body;
        
        public consultarUnicaDireccionResponse() {
        }
        
        public consultarUnicaDireccionResponse(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaDireccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarUnicaDireccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion consultarUnicaDireccionResult;
        
        public consultarUnicaDireccionResponseBody() {
        }
        
        public consultarUnicaDireccionResponseBody(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion consultarUnicaDireccionResult) {
            this.consultarUnicaDireccionResult = consultarUnicaDireccionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaGlobalSexoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaGlobalSexo", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultaGlobalSexoRequestBody Body;
        
        public consultaGlobalSexoRequest() {
        }
        
        public consultaGlobalSexoRequest(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultaGlobalSexoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultaGlobalSexoRequestBody {
        
        public consultaGlobalSexoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaGlobalSexoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaGlobalSexoResponse", Namespace="http://tempuri.org/", Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultaGlobalSexoResponseBody Body;
        
        public consultaGlobalSexoResponse() {
        }
        
        public consultaGlobalSexoResponse(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultaGlobalSexoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaGlobalSexoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.CatSexo[] consultaGlobalSexoResult;
        
        public consultaGlobalSexoResponseBody() {
        }
        
        public consultaGlobalSexoResponseBody(UTTT.Ejemplo.Persona.WinForm.Ejemplo.CatSexo[] consultaGlobalSexoResult) {
            this.consultaGlobalSexoResult = consultaGlobalSexoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EjemploSoapChannel : UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EjemploSoapClient : System.ServiceModel.ClientBase<UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap>, UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap {
        
        public EjemploSoapClient() {
        }
        
        public EjemploSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EjemploSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjemploSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjemploSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarPersonaResponse UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap.insertarPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarPersonaRequest request) {
            return base.Channel.insertarPersona(request);
        }
        
        public bool insertarPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona _persona) {
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarPersonaRequest inValue = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarPersonaRequest();
            inValue.Body = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarPersonaRequestBody();
            inValue.Body._persona = _persona;
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarPersonaResponse retVal = ((UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap)(this)).insertarPersona(inValue);
            return retVal.Body.insertarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarPersonaResponse UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap.editarPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarPersonaRequest request) {
            return base.Channel.editarPersona(request);
        }
        
        public bool editarPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona _persona) {
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarPersonaRequest inValue = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarPersonaRequest();
            inValue.Body = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarPersonaRequestBody();
            inValue.Body._persona = _persona;
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarPersonaResponse retVal = ((UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap)(this)).editarPersona(inValue);
            return retVal.Body.editarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarPersonaResponse UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap.eliminarPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarPersonaRequest request) {
            return base.Channel.eliminarPersona(request);
        }
        
        public bool eliminarPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona _persona) {
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarPersonaRequest inValue = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarPersonaRequest();
            inValue.Body = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarPersonaRequestBody();
            inValue.Body._persona = _persona;
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarPersonaResponse retVal = ((UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap)(this)).eliminarPersona(inValue);
            return retVal.Body.eliminarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalPersonaResponse UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap.consultarGlobalPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalPersonaRequest request) {
            return base.Channel.consultarGlobalPersona(request);
        }
        
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona[] consultarGlobalPersona() {
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalPersonaRequest inValue = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalPersonaRequest();
            inValue.Body = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalPersonaRequestBody();
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalPersonaResponse retVal = ((UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap)(this)).consultarGlobalPersona(inValue);
            return retVal.Body.consultarGlobalPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaPersonaResponse UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap.consultarUnicaPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaPersonaRequest request) {
            return base.Channel.consultarUnicaPersona(request);
        }
        
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona consultarUnicaPersona(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Persona _persona) {
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaPersonaRequest inValue = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaPersonaRequest();
            inValue.Body = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaPersonaRequestBody();
            inValue.Body._persona = _persona;
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaPersonaResponse retVal = ((UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap)(this)).consultarUnicaPersona(inValue);
            return retVal.Body.consultarUnicaPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarDireccionResponse UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap.insertarDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarDireccionRequest request) {
            return base.Channel.insertarDireccion(request);
        }
        
        public bool insertarDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion _direccion) {
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarDireccionRequest inValue = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarDireccionRequest();
            inValue.Body = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarDireccionRequestBody();
            inValue.Body._direccion = _direccion;
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.insertarDireccionResponse retVal = ((UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap)(this)).insertarDireccion(inValue);
            return retVal.Body.insertarDireccionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarDireccionResponse UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap.editarDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarDireccionRequest request) {
            return base.Channel.editarDireccion(request);
        }
        
        public bool editarDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion _direccion) {
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarDireccionRequest inValue = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarDireccionRequest();
            inValue.Body = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarDireccionRequestBody();
            inValue.Body._direccion = _direccion;
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.editarDireccionResponse retVal = ((UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap)(this)).editarDireccion(inValue);
            return retVal.Body.editarDireccionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarDireccionResponse UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap.eliminarDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarDireccionRequest request) {
            return base.Channel.eliminarDireccion(request);
        }
        
        public bool eliminarDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion _direccion) {
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarDireccionRequest inValue = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarDireccionRequest();
            inValue.Body = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarDireccionRequestBody();
            inValue.Body._direccion = _direccion;
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.eliminarDireccionResponse retVal = ((UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap)(this)).eliminarDireccion(inValue);
            return retVal.Body.eliminarDireccionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalDireccionResponse UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap.consultarGlobalDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalDireccionRequest request) {
            return base.Channel.consultarGlobalDireccion(request);
        }
        
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion[] consultarGlobalDireccion() {
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalDireccionRequest inValue = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalDireccionRequest();
            inValue.Body = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalDireccionRequestBody();
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarGlobalDireccionResponse retVal = ((UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap)(this)).consultarGlobalDireccion(inValue);
            return retVal.Body.consultarGlobalDireccionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaDireccionResponse UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap.consultarUnicaDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaDireccionRequest request) {
            return base.Channel.consultarUnicaDireccion(request);
        }
        
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion consultarUnicaDireccion(UTTT.Ejemplo.Persona.WinForm.Ejemplo.Direccion _direccion) {
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaDireccionRequest inValue = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaDireccionRequest();
            inValue.Body = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaDireccionRequestBody();
            inValue.Body._direccion = _direccion;
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultarUnicaDireccionResponse retVal = ((UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap)(this)).consultarUnicaDireccion(inValue);
            return retVal.Body.consultarUnicaDireccionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultaGlobalSexoResponse UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap.consultaGlobalSexo(UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultaGlobalSexoRequest request) {
            return base.Channel.consultaGlobalSexo(request);
        }
        
        public UTTT.Ejemplo.Persona.WinForm.Ejemplo.CatSexo[] consultaGlobalSexo() {
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultaGlobalSexoRequest inValue = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultaGlobalSexoRequest();
            inValue.Body = new UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultaGlobalSexoRequestBody();
            UTTT.Ejemplo.Persona.WinForm.Ejemplo.consultaGlobalSexoResponse retVal = ((UTTT.Ejemplo.Persona.WinForm.Ejemplo.EjemploSoap)(this)).consultaGlobalSexo(inValue);
            return retVal.Body.consultaGlobalSexoResult;
        }
    }
}
